
version: '3.1'

services:

  apache-nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - 8080:8443
    environment:
      NIFI_WEB_PROXY_HOST: 192.168.1.12:8080
      AUTH: tls
      KEYSTORE_PATH: /opt/certs/client.pfx
      KEYSTORE_TYPE: PKCS12
      KEYSTORE_PASSWORD: Password123
      TRUSTSTORE_PATH: /opt/certs/truststore.jks
      TRUSTSTORE_TYPE: JKS
      TRUSTSTORE_PASSWORD: Password123
    volumes:
      - ./certs:/opt/certs
      - ./conf:/opt/nifi/nifi-current/conf